#!/usr/bin/env bash
#
# gen-theme.sh — seed から「一貫性 + コントラスト保証」付きの theme を決定論生成する (Lv1)。
#
# DESIGN-CEILING.md の Lv1「静的デザインシステム生成」。少数の seed から
#   - type scale (modular scale: base × ratio^n)
#   - spacing scale (8px グリッド: space × n)
#   - palette (HSL から生成し、全 fg/bg ペアの WCAG コントラストを計算して AA 以上を保証)
# を導出し、md-to-html 互換の report-theme-head.html (<style> ブロック) を出力する。
#
# 「正しさ (一貫性・アクセシビリティ・原則準拠) はコードで保証できる」を実演する側。
# 生成物は design-audit.sh を 0 FAIL/WARN で通る (生成→監査のループが閉じる)。
#
# 使い方:
#   ./gen-theme.sh [--base 16] [--ratio 1.25] [--space 8] [--hue 245] [--hue2 270] [--out <file>]
#   --out 省略時は標準出力 (既存 asset を破壊しない)。
#
# 注: 色調和は本来 OKLCH が望ましいが、ここでは HSL + コントラスト駆動の明度調整で
# 「コントラスト保証」を担保する (目的は満たす。OKLCH 化は将来の改善)。
#
set -euo pipefail

BASE=16; RATIO=1.25; SPACE=8; HUE=245; HUE2=270; OUT=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --base)  BASE="$2"; shift 2 ;;
    --ratio) RATIO="$2"; shift 2 ;;
    --space) SPACE="$2"; shift 2 ;;
    --hue)   HUE="$2"; shift 2 ;;
    --hue2)  HUE2="$2"; shift 2 ;;
    --out)   OUT="$2"; shift 2 ;;
    -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

# --- seed → トークン/サイズを awk で生成 (KEY=VALUE で出力) ----------------
gen="$(awk -v base="$BASE" -v ratio="$RATIO" -v space="$SPACE" -v hue="$HUE" -v hue2="$HUE2" '
function hue2rgb(p,q,t){ if(t<0)t+=1; if(t>1)t-=1;
  if(t<1/6) return p+(q-p)*6*t;
  if(t<1/2) return q;
  if(t<2/3) return p+(q-p)*(2/3-t)*6;
  return p }
function clampL(l){ if(l<0)return 0; if(l>1)return 1; return l }
function hslhex(h,s,l,   r,g,b,q,p,hk){
  h=h%360; if(h<0)h+=360; hk=h/360;
  if(s==0){ r=l; g=l; b=l } else {
    q=(l<0.5)? l*(1+s) : l+s-l*s; p=2*l-q;
    r=hue2rgb(p,q,hk+1/3); g=hue2rgb(p,q,hk); b=hue2rgb(p,q,hk-1/3) }
  return sprintf("#%02x%02x%02x", int(r*255+0.5), int(g*255+0.5), int(b*255+0.5)) }
function hexv(s,   n,i,c,d){ s=tolower(s); gsub(/#/,"",s); n=0
  for(i=1;i<=length(s);i++){ c=substr(s,i,1); d=index("0123456789abcdef",c)-1; if(d<0)d=0; n=n*16+d }
  return n }
function lin(v){ v=v/255; return (v<=0.03928)? v/12.92 : ((v+0.055)/1.055)^2.4 }
function lum(h,  r,g,b){ gsub(/#/,"",h); r=hexv(substr(h,1,2)); g=hexv(substr(h,3,2)); b=hexv(substr(h,5,2));
  return 0.2126*lin(r)+0.7152*lin(g)+0.0722*lin(b) }
function cratio(a,b,  l1,l2,t){ l1=lum(a)+0.05; l2=lum(b)+0.05; if(l2>l1){t=l1;l1=l2;l2=t} return l1/l2 }
# 明度を動かして bg に対し target コントラスト以上にする (保証ループ)
function adjust(h,s,l,bg,target,lighten,   hex,c,steps){
  for(steps=0; steps<80; steps++){
    hex=hslhex(h,s,clampL(l)); c=cratio(hex,bg);
    if(c>=target) return hex;
    l = lighten? l+0.012 : l-0.012;
    if(l<=0 || l>=1) return hslhex(h,s,clampL(l));
  }
  return hslhex(h,s,clampL(l)) }
function rnd(x){ return int(x+0.5) }
BEGIN{
  # --- サイズ (modular type scale) ---
  print "body=" rnd(base)
  print "h3="   rnd(base*ratio)
  print "h2="   rnd(base*(ratio^2))
  print "h1="   rnd(base*(ratio^3))
  print "h1m="  rnd(base*(ratio^3)*0.82)
  print "small="rnd(base*0.875)
  print "measure=" rnd(38*base)
  print "lh=1.7"; print "container=1100"
  # --- spacing (8px グリッド) ---
  print "space1=" rnd(space*1); print "space2=" rnd(space*2); print "space3=" rnd(space*3)
  print "space4=" rnd(space*4); print "space5=" rnd(space*5); print "space6=" rnd(space*6)
  print "space8=" rnd(space*10)
  # --- 画面 (ダーク) パレット: bg を起点に各色を AA 保証 ---
  bg=hslhex(hue,0.16,0.07)
  print "bg=" bg
  print "surface="  hslhex(hue,0.15,0.11)
  print "surface2=" hslhex(hue,0.14,0.16)
  print "border="   hslhex(hue,0.12,0.23)
  print "text="     adjust(hue,0.12,0.92,bg,7.0,1)
  print "textsub="  adjust(hue,0.10,0.62,bg,4.5,1)
  print "accent="   adjust(hue,0.90,0.70,bg,4.5,1)
  print "accent2="  adjust(hue2,0.80,0.74,bg,4.5,1)
  print "green="    adjust(145,0.60,0.55,bg,4.5,1)
  print "yellow="   adjust(45,0.85,0.60,bg,4.5,1)
  print "red="      adjust(2,0.80,0.66,bg,4.5,1)
  print "cyan="     adjust(190,0.70,0.55,bg,4.5,1)
  # --- 印刷 (ライト) パレット: 白地に AA 保証 ---
  pbg="#ffffff"
  print "pbg=" pbg
  print "psurface=#ffffff"
  print "psurface2=" hslhex(hue,0.10,0.96)
  print "pborder="   hslhex(hue,0.10,0.86)
  print "ptext="     adjust(hue,0.30,0.16,pbg,7.0,0)
  print "ptextsub="  adjust(hue,0.18,0.40,pbg,4.5,0)
  print "paccent="   adjust(hue,0.75,0.45,pbg,4.5,0)
  print "paccent2="  adjust(hue2,0.60,0.50,pbg,4.5,0)
  print "pgreen="    adjust(145,0.70,0.35,pbg,4.5,0)
  print "pyellow="   adjust(40,0.95,0.33,pbg,4.5,0)
  print "pred="      adjust(2,0.75,0.45,pbg,4.5,0)
  print "pcyan="     adjust(190,0.90,0.32,pbg,4.5,0)
}')"

declare -A T
while IFS='=' read -r k v; do
  [[ -n "$k" ]] && T["$k"]="$v"
done <<< "$gen"

# --- <style> ブロックを組み立て ------------------------------------------
emit() {
cat <<STYLE_EOF
<!--
  GENERATED by gen-theme.sh (Lv1: seed → デザインシステム生成)
  seed: base=${BASE} ratio=${RATIO} space=${SPACE} hue=${HUE} hue2=${HUE2}
  type scale / spacing / palette は seed から決定論導出。色は全 fg/bg ペアの
  WCAG コントラストを計算して AA 以上を保証済み。手編集せず gen-theme.sh で再生成する。
-->
<style>
  :root {
    --bg: ${T[bg]}; --surface: ${T[surface]}; --surface2: ${T[surface2]}; --border: ${T[border]};
    --text: ${T[text]}; --text-sub: ${T[textsub]};
    --accent: ${T[accent]}; --accent2: ${T[accent2]};
    --green: ${T[green]}; --yellow: ${T[yellow]}; --red: ${T[red]}; --cyan: ${T[cyan]};
    --measure: ${T[measure]}px;
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Hiragino Sans','Noto Sans JP','Noto Sans CJK JP',-apple-system,sans-serif;
         background: var(--bg); color: var(--text); line-height: ${T[lh]}; }
  .container { max-width: ${T[container]}px; margin: 0 auto; padding: ${T[space5]}px ${T[space3]}px ${T[space8]}px; }
  h1 { font-size: ${T[h1]}px; font-weight: 700; margin-bottom: ${T[space1]}px; }
  h1 span { color: var(--accent); }
  .subtitle { color: var(--text-sub); font-size: ${T[small]}px; margin-bottom: ${T[space6]}px; }
  h2 { font-size: ${T[h2]}px; font-weight: 700; margin: ${T[space6]}px 0 ${T[space3]}px; padding-bottom: ${T[space1]}px;
       border-bottom: 2px solid var(--accent); display: inline-block; }
  h3 { font-size: ${T[h3]}px; font-weight: 600; color: var(--accent2); margin: ${T[space4]}px 0 ${T[space2]}px; }
  .card { background: var(--surface); border: 1px solid var(--border); border-radius: 12px; padding: ${T[space3]}px; margin-bottom: ${T[space3]}px; }
  .card-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: ${T[space2]}px; margin-bottom: ${T[space3]}px; }
  .card-sm { background: var(--surface2); border: 1px solid var(--border); border-radius: 8px; padding: ${T[space2]}px; }
  .card-sm .label { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; color: var(--text-sub); margin-bottom: 6px; }
  .card-sm .value { font-size: ${T[h3]}px; font-weight: 700; }
  .card-sm .desc { font-size: 13px; color: var(--text-sub); margin-top: 4px; }
  .tag { display: inline-block; padding: 2px 10px; border-radius: 4px; font-size: 12px; font-weight: 600; margin-right: 6px; }
  .tag-blue   { background: color-mix(in srgb, var(--accent) 15%, transparent);  color: var(--accent); }
  .tag-purple { background: color-mix(in srgb, var(--accent2) 15%, transparent); color: var(--accent2); }
  .tag-green  { background: color-mix(in srgb, var(--green) 15%, transparent);   color: var(--green); }
  .tag-yellow { background: color-mix(in srgb, var(--yellow) 15%, transparent);  color: var(--yellow); }
  .tag-red    { background: color-mix(in srgb, var(--red) 15%, transparent);     color: var(--red); }
  .tag-cyan   { background: color-mix(in srgb, var(--cyan) 15%, transparent);    color: var(--cyan); }
  table { width: 100%; border-collapse: collapse; margin: ${T[space2]}px 0; font-size: 14px; }
  th { text-align: left; padding: 10px 12px; background: var(--surface2); color: var(--text-sub); font-weight: 600;
       font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 1px solid var(--border); }
  td { padding: 10px 12px; border-bottom: 1px solid var(--border); vertical-align: top; }
  tr:last-child td { border-bottom: none; }
  .highlight-box { background: color-mix(in srgb, var(--accent) 6%, transparent); border: 1px solid color-mix(in srgb, var(--accent) 25%, transparent); border-radius: 8px; padding: 14px 16px; margin: ${T[space2]}px 0; }
  .highlight-box .title { color: var(--accent); font-weight: 700; font-size: 13px; margin-bottom: 6px; }
  .highlight-box p, .highlight-box li { font-size: 13px; color: var(--text-sub); }
  .highlight-box strong { color: var(--text); }
  .highlight-box ul { padding-left: 18px; margin-top: 6px; }
  .warn-box { background: color-mix(in srgb, var(--yellow) 6%, transparent); border: 1px solid color-mix(in srgb, var(--yellow) 22%, transparent); border-radius: 8px; padding: 14px 16px; margin: ${T[space2]}px 0; }
  .warn-box .title { color: var(--yellow); font-weight: 700; font-size: 13px; margin-bottom: 6px; }
  .warn-box p, .warn-box li { font-size: 13px; color: var(--text-sub); }
  .warn-box strong { color: var(--text); }
  .risk-box { background: color-mix(in srgb, var(--red) 6%, transparent); border: 1px solid color-mix(in srgb, var(--red) 22%, transparent); border-radius: 8px; padding: 14px 16px; margin: ${T[space2]}px 0; }
  .risk-box .title { color: var(--red); font-weight: 700; font-size: 13px; margin-bottom: 6px; }
  .risk-box p, .risk-box li { font-size: 13px; color: var(--text-sub); }
  .risk-box strong { color: var(--text); }
  .ok-box { background: color-mix(in srgb, var(--green) 6%, transparent); border: 1px solid color-mix(in srgb, var(--green) 22%, transparent); border-radius: 8px; padding: 14px 16px; margin: ${T[space2]}px 0; }
  .ok-box .title { color: var(--green); font-weight: 700; font-size: 13px; margin-bottom: 6px; }
  .ok-box p, .ok-box li { font-size: 13px; color: var(--text-sub); }
  .ok-box strong { color: var(--text); }
  blockquote { border-left: 3px solid var(--accent2); padding: 8px 14px; margin: 10px 0;
               background: color-mix(in srgb, var(--accent2) 5%, transparent); font-size: 13px; color: var(--text-sub); font-style: italic; }
  blockquote strong { color: var(--text); font-style: normal; }
  .divider, hr { border: none; border-top: 1px solid var(--border); margin: ${T[space6]}px 0; }
  .note { font-size: 13px; color: var(--text-sub); padding: 12px 16px; background: var(--surface2); border-radius: 8px; border-left: 3px solid var(--accent); margin: ${T[space2]}px 0; }
  pre { background: var(--surface2); border: 1px solid var(--border); border-radius: 8px; padding: 14px 16px; margin: ${T[space2]}px 0; overflow-x: auto;
        font-family: ui-monospace,'SFMono-Regular',Menlo,Consolas,monospace; font-size: 12.5px; line-height: 1.5; color: var(--text); }
  code { font-family: ui-monospace,'SFMono-Regular',Menlo,Consolas,monospace; font-size: 0.88em; background: var(--surface2); border: 1px solid var(--border); border-radius: 4px; padding: 1px 5px; color: var(--cyan); }
  pre code { background: none; border: none; padding: 0; color: inherit; font-size: inherit; }
  ul, ol { padding-left: 22px; margin: 10px 0; }
  li { margin: 3px 0; }
  a { color: var(--accent); text-decoration: none; }
  a:hover { text-decoration: underline; }
  .container > p, .container > ul, .container > ol, blockquote { max-width: var(--measure); }
  .vflow { display: flex; flex-direction: column; align-items: center; gap: 0; margin: 20px auto; max-width: 700px; }
  .flow-node { background: var(--surface2); border: 1px solid var(--border); border-radius: 10px; padding: 12px 18px; text-align: center; width: 100%; max-width: 500px; }
  .flow-node .role { font-size: 11px; color: var(--text-sub); margin-bottom: 4px; }
  .flow-node .action { font-size: 13px; font-weight: 600; }
  .flow-node.highlight { border-color: var(--accent); background: color-mix(in srgb, var(--accent) 8%, transparent); }
  .flow-node.highlight-green { border-color: var(--green); background: color-mix(in srgb, var(--green) 8%, transparent); }
  .flow-node.highlight-purple { border-color: var(--accent2); background: color-mix(in srgb, var(--accent2) 8%, transparent); }
  .flow-arrow-down { text-align: center; color: var(--text-sub); font-size: 20px; padding: 6px 0; }
  @media (max-width: 768px) {
    .container { padding: ${T[space3]}px ${T[space2]}px ${T[space6]}px; }
    .card-grid { grid-template-columns: 1fr; }
    h1 { font-size: ${T[h1m]}px; }
    table { display: block; width: max-content; max-width: 100%; overflow-x: auto; }
  }
  @media print {
    @page { size: A4; margin: 8mm 10mm; }
    :root {
      --bg: ${T[pbg]}; --surface: ${T[psurface]}; --surface2: ${T[psurface2]}; --border: ${T[pborder]};
      --text: ${T[ptext]}; --text-sub: ${T[ptextsub]}; --accent: ${T[paccent]}; --accent2: ${T[paccent2]};
      --green: ${T[pgreen]}; --yellow: ${T[pyellow]}; --red: ${T[pred]}; --cyan: ${T[pcyan]};
      --measure: none;
    }
    body { background: #fff; color: var(--text); font-size: 9px; line-height: 1.35; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .container { max-width: 100%; padding: 0; }
    h1 { font-size: 16px; margin-bottom: 2px; }
    h2 { font-size: 12px; margin: 8px 0 4px; padding-bottom: 2px; page-break-after: avoid; }
    h3 { font-size: 11px; margin: 6px 0 3px; page-break-after: avoid; }
    p { margin-bottom: 3px; font-size: 9px; }
    .subtitle { margin-bottom: 6px; font-size: 9px; }
    .divider, hr { margin: 6px 0; }
    .card { padding: 6px 8px; margin-bottom: 4px; break-inside: avoid; border-radius: 4px; }
    .card p { line-height: 1.4; }
    .card-grid { gap: 4px; margin-bottom: 4px; }
    .card-sm { padding: 4px 6px; break-inside: avoid; border-radius: 4px; }
    .card-sm .label { font-size: 7px; margin-bottom: 1px; }
    .card-sm .value { font-size: 11px; }
    .card-sm .desc { font-size: 8px; margin-top: 1px; }
    table { font-size: 8px; margin: 3px 0; }
    th { padding: 3px 4px; font-size: 7px; }
    td { padding: 3px 4px; }
    .tag { border: 1px solid currentColor; padding: 0 4px; font-size: 7px; }
    .highlight-box, .warn-box, .risk-box, .ok-box { padding: 5px 8px; margin: 4px 0; break-inside: avoid; border-radius: 4px; }
    .highlight-box .title, .warn-box .title, .risk-box .title, .ok-box .title { font-size: 9px; margin-bottom: 2px; }
    .highlight-box p, .warn-box p, .risk-box p, .ok-box p,
    .highlight-box li, .warn-box li, .risk-box li, .ok-box li { font-size: 8px; }
    blockquote { font-size: 8px; padding: 4px 8px; }
    .vflow { margin: 4px auto; }
    .flow-node { padding: 3px 8px; break-inside: avoid; border-radius: 4px; }
    .flow-node .role { font-size: 7px; margin-bottom: 1px; }
    .flow-node .action { font-size: 8px; }
    .flow-arrow-down { padding: 1px 0; font-size: 12px; line-height: 1; }
    .note { padding: 4px 8px; font-size: 8px; margin: 4px 0; border-radius: 4px; }
    pre { font-size: 7.5px; padding: 5px 7px; break-inside: avoid; border-radius: 4px; }
    code { font-size: 0.85em; padding: 0 2px; }
    ul, ol { padding-left: 16px; margin: 4px 0; }
    li { margin: 1px 0; }
    .card, .flow-node { page-break-inside: avoid; }
  }
</style>
STYLE_EOF
}

if [[ -n "$OUT" ]]; then
  if ! emit > "$OUT"; then
    echo "error: 書き込み失敗: $OUT" >&2; exit 1
  fi
  echo "generated: ${OUT}"
  echo "  seed: base=${BASE} ratio=${RATIO} space=${SPACE} hue=${HUE} hue2=${HUE2}"
  echo "  type scale: ${T[body]}/${T[h3]}/${T[h2]}/${T[h1]}px  spacing: ${T[space1]}/${T[space2]}/${T[space3]}/${T[space4]}/${T[space6]}px"
else
  emit
fi
